# image: udhaygithub/udhay_playwright
# image: udhaygithub-udhay_playwright
# image: gitpod/udhaygithub-udhay_playwright
image: gitpod/udhaygithub/udhay_playwright

# Commands that will run on workspace start
tasks:
    - name: Setup, Install & Build
      before: yarn global add express
      init: yarn install
      command: yarn build

# Ports to expose on workspace startup
ports:
    - port: 3000
      onOpen: open-preview
      name: Website
      description: Website Preview
      visibility: private
      protocol: https